#spring.application.name=xzlenzv3
##server.address=0.0.0.0
#server.port=8091
#spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
#
#
#
#spring.profiles.active=local
##spring.profiles.active=dev
##spring.profiles.active=prod
#
#app.dev.recipients=ashutosh.sharma@cybercube.co,ashish.kumar@cybercube.co
#auth.master-password=Your$trongMasterP@ssw0rd
#
#
#spring.jpa.hibernate.ddl-auto=update
##spring.jpa.properties.hibernate.current_session_context_class=org.springframework.orm.hibernate5.SpringSessionContext
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#
#
#
#
#
#server.servlet.context-path=/xzlenzv3
#
#upload.dir=xzlenzv3
#
#jwt.secret=xzlenz_secret_key
#
#
#
#spring.servlet.multipart.max-file-size=100MB
#spring.servlet.multipart.max-request-size=100MB
#server.tomcat.max-swallow-size=100MB
#
#
#
##logging.level.root=DEBUG
##logging.level.org.springframework.security=DEBUG
