spring:
  application:
    name: xzlenzv3
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

server:
  #address: 0.0.0.0
  port: 8091
  servlet:
    context-path: /xzlenzv3
  tomcat:
    max-swallow-size: 100MB

app:
  dev:
    recipients: "ashutosh.sharma@cybercube.co,ashish.kumar@cybercube.co"

auth:
  master-password: "Your$trongMasterP@ssw0rd"

upload:
  dir: xzlenzv3

jwt:
  secret: xzlenz_secret_key

#logging:
#  level:
#    root: DEBUG
#    org.springframework.security: DEBUG
